# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-10 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dreams',
            fields=[
                ('dreams_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('dream_date', models.DateTimeField()),
                ('is_lucid', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Dream',
                'verbose_name_plural': 'Dreams',
            },
        ),
    ]
